# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminshop', '0002_compras_enviar_policia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantias',
            name='ns_imei',
        ),
    ]
