# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminshop', '0003_remove_garantias_ns_imei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsendgestoria',
            options={'ordering': ['-fecha_creado']},
        ),
        migrations.AlterModelOptions(
            name='documentsendpolice',
            options={'ordering': ['-fecha_creado']},
        ),
        migrations.RemoveField(
            model_name='documentsendgestoria',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='documentsendpolice',
            name='fecha',
        ),
        migrations.AddField(
            model_name='documentsendgestoria',
            name='envidado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsendgestoria',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsendgestoria',
            name='intervalo',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsendpolice',
            name='envidado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsendpolice',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentsendpolice',
            name='intervalo',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abonos',
            name='forma_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TJ', 'Tarjeta'), ('TB', 'Transferencia bancaria')], default='EF', max_length=2),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='forma_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TJ', 'Tarjeta'), ('TB', 'Transferencia bancaria')], default='EF', max_length=2),
        ),
    ]
