# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminshop', '0004_auto_20180202_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsendgestoria',
            old_name='envidado',
            new_name='enviado',
        ),
        migrations.RenameField(
            model_name='documentsendpolice',
            old_name='envidado',
            new_name='enviado',
        ),
    ]
